# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

format = """
$python$directory $git_branch$git_status$git_state$git_commit$character
"""

right_format = """
$cmd_duration
"""

add_newline = false

[character]
success_symbol = "[ ](bold fg:blue)"
error_symbol = "[  ](bold fg:red)"
vimcmd_symbol = "[](bold fg:green)"


[git_branch]
format = "[[\\[$symbol$branch](rosewater) | ](peach)"
symbol = "  "

[git_status]
format = "$all_status$ahead_behind\\] "
conflicted = "="
ahead = "[⇡${count} ](green)"
behind = "⇣${count} "
diverged = "[⇕⇡${ahead_count} ⇣${behind_count} ](teal)"
up_to_date = "[󰄸 ](bold green)"
untracked = "[?${count} ](maroon)"
stashed = "[󰏖  ](bold green)"
modified = "[~${count} ](yellow)"
staged = "[+${count} ](green)"
renamed = "[»${count} ](peach)"
# deleted = "[ ${count} ](bold red)"
deleted = "[-${count} ](bold red)"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[python]
symbol = " "
format = '(\($virtualenv\) )($style)'

[cmd_duration]
min_time = 10
format = '󰥔 [$duration](bold purple)'
show_milliseconds = true



[directory]
home_symbol = "  "
read_only = "  "
style = "fg:yellow "
# truncation_length = 6
# truncation_symbol = " ••/"
fish_style_pwd_dir_length = 1
format = '[󰉋 $path]($style)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
